# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training_backend.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='training_backend.proto',
  package='training_analyser',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16training_backend.proto\x12\x11training_analyser\"\x07\n\x05\x45mpty\"Z\n\x0c\x46itnessTrend\x12\r\n\x05\x64\x61tes\x18\x01 \x03(\t\x12\x0f\n\x07\x66\x61tigue\x18\x02 \x03(\x01\x12\x0f\n\x07\x66itness\x18\x03 \x03(\x01\x12\x0c\n\x04\x66orm\x18\x04 \x03(\x01\x12\x0b\n\x03tss\x18\x05 \x03(\x01\x32\xaa\x01\n\x0eTrainingTrends\x12H\n\x10UpdateActivities\x12\x18.training_analyser.Empty\x1a\x18.training_analyser.Empty\"\x00\x12N\n\x0fGetFitnessTrend\x12\x18.training_analyser.Empty\x1a\x1f.training_analyser.FitnessTrend\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='training_analyser.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=52,
)


_FITNESSTREND = _descriptor.Descriptor(
  name='FitnessTrend',
  full_name='training_analyser.FitnessTrend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dates', full_name='training_analyser.FitnessTrend.dates', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fatigue', full_name='training_analyser.FitnessTrend.fatigue', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fitness', full_name='training_analyser.FitnessTrend.fitness', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='form', full_name='training_analyser.FitnessTrend.form', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tss', full_name='training_analyser.FitnessTrend.tss', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['FitnessTrend'] = _FITNESSTREND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'training_backend_pb2'
  # @@protoc_insertion_point(class_scope:training_analyser.Empty)
  })
_sym_db.RegisterMessage(Empty)

FitnessTrend = _reflection.GeneratedProtocolMessageType('FitnessTrend', (_message.Message,), {
  'DESCRIPTOR' : _FITNESSTREND,
  '__module__' : 'training_backend_pb2'
  # @@protoc_insertion_point(class_scope:training_analyser.FitnessTrend)
  })
_sym_db.RegisterMessage(FitnessTrend)



_TRAININGTRENDS = _descriptor.ServiceDescriptor(
  name='TrainingTrends',
  full_name='training_analyser.TrainingTrends',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=147,
  serialized_end=317,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateActivities',
    full_name='training_analyser.TrainingTrends.UpdateActivities',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFitnessTrend',
    full_name='training_analyser.TrainingTrends.GetFitnessTrend',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_FITNESSTREND,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAININGTRENDS)

DESCRIPTOR.services_by_name['TrainingTrends'] = _TRAININGTRENDS

# @@protoc_insertion_point(module_scope)
